apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ns.yaml
  - redis.yaml
  - payment.yaml
  - subscription.yaml
  - ingress.yaml

secretGenerator:
  - name: redis-secrets
    namespace: sns
    type: Opaque
    files:
      - secrets/redis.conf
      - secrets/redis_password
  - name: ingress-tls
    namespace: sns
    type: "kubernetes.io/tls"
    files:
      - tls.crt=secrets/cert.pem
      - tls.key=secrets/key.pem

configMapGenerator:
  - name: sns-config
    behavior: create
    namespace: sns
    files:
      - config/config.production.json
