apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- redis.yaml
- payment.yaml
- subscription.yaml

secretGenerator:
  - name: redis-secrets
    namespace: sns
    files:
      - secrets/redis.conf
      - secrets/redis_password
    type: Opaque

configMapGenerator:
  - name: sns-config
    behavior: create
    namespace: sns
    files:
      - config/config.production.json
