apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: appuser
      securityContext:
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: redis
          image: redis:6.2.1-alpine
          args:
            - "/usr/local/etc/redis/redis.conf"
            - "--appendonly"
            - "yes"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 125m
              memory: 85Mi
            limits:
              cpu: 250m
              memory: 160Mi
          volumeMounts:
            - name: redis-cfg
              readOnly: true
              mountPath: "/usr/local/etc/redis"
            - name: redis-vol
              mountPath: "/data"
          securityContext:
            runAsUser: 999
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      volumes:
        - name: redis-cfg
          secret:
            secretName: redis-secrets
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-vol
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
  selector:
    app: redis
